using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace CustomMapper.SourceGenerator.Generator
{
    internal static class SourceGenerationHelper
    {
        internal const string ExtendMapMethodName = "ExtendMap";

        private const string IMapperGlobal = "global::CustomMapper.SourceGenerator.Runtime.IMapper";

        public static string HintName(MapperClassModel model)
        {
            var prefix = model.NamespaceName is { Length: > 0 } ? model.NamespaceName + "." : string.Empty;
            return $"{prefix}{model.ClassName}.g.cs";
        }

        public static string MapperClass(MapperClassModel model)
        {
            var sb = new SourceBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");

            bool hasNamespace = !string.IsNullOrEmpty(model.NamespaceName);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {model.NamespaceName}");
                sb.OpenBrace();
            }

            var contracts = model.Methods.AsImmutableArray()
                .Select(m => $"{IMapperGlobal}<{m.SourceTypeGlobal}, {m.DestinationTypeGlobal}>")
                .Distinct()
                .ToList();

            sb.AppendLine($"partial class {model.ClassName} : {string.Join(", ", contracts)}");
            sb.OpenBrace();

            foreach (var method in model.Methods.AsImmutableArray())
            {
                EmitMapMethod(sb, method);
                sb.AppendLine();
            }

            EmitInterfaceShims(sb, model);

            sb.CloseBrace();

            if (hasNamespace)
                sb.CloseBrace();

            return sb.ToString();
        }

        public static string Registration(ImmutableArray<MapperClassModel> models)
        {
            var pairs = new List<(string Source, string Destination, string ImplGlobal)>();
            foreach (var model in models)
            {
                var implGlobal = model.NamespaceName is { Length: > 0 }
                    ? $"global::{model.NamespaceName}.{model.ClassName}"
                    : $"global::{model.ClassName}";

                foreach (var method in model.Methods.AsImmutableArray())
                    pairs.Add((method.SourceTypeGlobal, method.DestinationTypeGlobal, implGlobal));
            }

            var sb = new SourceBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace CustomMapper.SourceGenerator");
            sb.OpenBrace();
            sb.AppendLine("public static class GeneratedMapperRegistration");
            sb.OpenBrace();
            sb.AppendLine("public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedMappers(");
            sb.AppendLine("    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
            sb.AppendLine("    global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime");
            sb.AppendLine("        = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped)");
            sb.OpenBrace();

            foreach (var pair in pairs)
            {
                sb.AppendLine("services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(");
                sb.AppendLine($"    typeof({IMapperGlobal}<{pair.Source}, {pair.Destination}>),");
                sb.AppendLine($"    typeof({pair.ImplGlobal}), lifetime));");
            }

            sb.AppendLine();
            sb.AppendLine("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions");
            sb.AppendLine($"    .TryAddTransient<{IMapperGlobal},");
            sb.AppendLine("                     global::CustomMapper.SourceGenerator.Runtime.MapperImplementation>(services);");
            sb.AppendLine("return services;");
            sb.CloseBrace();
            sb.CloseBrace();
            sb.CloseBrace();
            return sb.ToString();
        }

        private static void EmitMapMethod(SourceBuilder sb, MapMethodModel method)
        {
            sb.AppendLine($"public partial {method.DestinationTypeGlobal} {method.MethodName}({method.SourceTypeGlobal} source)");
            sb.OpenBrace();
            sb.AppendLine($"var destination = new {method.DestinationTypeGlobal}();");
            foreach (var a in method.Assignments.AsImmutableArray())
                sb.AppendLine($"destination.{a.DestinationProperty} = source.{a.SourceProperty};");
            if (method.HasExtendMap)
                sb.AppendLine($"{ExtendMapMethodName}(source, destination);");
            sb.AppendLine("return destination;");
            sb.CloseBrace();
        }

        private static void EmitInterfaceShims(SourceBuilder sb, MapperClassModel model)
        {
            foreach (var method in model.Methods.AsImmutableArray())
            {
                if (method.MethodName == "Map") continue;
                sb.AppendLine(
                    $"{method.DestinationTypeGlobal} {IMapperGlobal}<{method.SourceTypeGlobal}, {method.DestinationTypeGlobal}>.Map({method.SourceTypeGlobal} source) => this.{method.MethodName}(source);");
                sb.AppendLine();
            }
        }
    }
}
